"""ingestion queue: content, attempts, pending index

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 10:05:05.646986

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("content", sa.Text(), nullable=True))
    op.add_column(
        "documents", sa.Column("attempts", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_index(
        "ix_documents_pending",
        "documents",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'processing')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_documents_pending",
        table_name="documents",
        postgresql_where=sa.text("status IN ('queued', 'processing')"),
    )
    op.drop_column("documents", "attempts")
    op.drop_column("documents", "content")
    # ### end Alembic commands ###
